name: Ruby CI/CD for Development

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.1' 

    - name: Install dependencies
      run: bundle install

    - name: Install bundler-audit
      run: gem install bundler-audit

    - name: Run bundler-audit
      run: bundler-audit check --update

    - name: Run linter
      run: bundle exec rubocop

    - name: Run tests
      run: bundle exec rspec --init

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/ruby-app:latest
          ${{ secrets.DOCKER_USERNAME }}/ruby-app:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ruby-app:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/ruby-app:buildcache,mode=max
