name: Ruby CI/CD for Development

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.1' 

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rspec --init
